http:
  port: 8080
admin:
  port: 9876
  host: localhost

apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  auth:
    host: localhost
    paths: ["/auth", "/auth/*"]
  mail:
    host: localhost
    paths: ["/mail", "/mail/*"]

serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  authService:
    url: "http://localhost:3000"
  mailService:
    url: "http://localhost:8000"

policies:
  - cors
  - log
  - proxy
  - rate-limit

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - cors:
          - action:
              origin: "${ORIGIN_FE_URL}"
              methods: ["GET", "POST", "DELETE", "PUT", "PATCH"]
              credentials: true
              allowedHeaders:
                ["Authorization", "Content-Type", "X-Requested-With"]
      - log:
          - action:
              message: "Incoming request: {method} {url}"
      - proxy:
          - action:
              serviceEndpoint: authService
      - proxy:
          - action:
              serviceEndpoint: mailService

  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true

  mailPipeline:
    apiEndpoints:
      - mail
    policies:
      - proxy:
          - action:
              serviceEndpoint: mailService
              changeOrigin: true
